### ISSUE TITLE
odd missing geometry thats only present on mario 

### ISSUE THREAD

**Issue by Kaiotiq** [Sage-of-Mirrors/BMDCubed#4]
seems to be a problem when a model has more than 8 textures i think, but parts of the geometry seems to be invisible in spots that contain a particular texture
if you put 1 texture over all of the mesh, the issue seems to disappear

**Comment by Sage-of-Mirrors** [comment]
Upon further investigation, it was determined that the missing geometry on Mario was the result of the game itself capping Mario's model at 3 total textures. The missing geometry was not related to BMDCubed.
